export interface SubmoduleConfig {
  id: string;
  label: string;
  description?: string;
  badge?: string;
}

export interface ModuleConfig {
  id: string;
  code: string;
  label: string;
  route: string;
  iconName: string;
  description: string;
  submodules: SubmoduleConfig[];
}

export const MODULE_REGISTRY: ModuleConfig[] = [
  {
    id: 'dashboard',
    code: '01',
    label: 'Dashboard',
    route: '/',
    iconName: 'LayoutDashboard',
    description: 'Executive command center, role dashboards, and high-level institutional health',
    submodules: [
      { id: 'overview', label: 'Overview' },
      { id: 'operations', label: "Today's Operations" },
      { id: 'alerts', label: 'Alerts & Attention' },
      { id: 'upcoming', label: 'Upcoming' },
      { id: 'tasks', label: 'My Tasks' },
      { id: 'quick-actions', label: 'Quick Actions' },
      { id: 'role-dashboard', label: 'Role Dashboard' },
    ],
  },
  {
    id: 'admissions',
    code: '02',
    label: 'Admissions',
    route: '/admissions',
    iconName: 'UserSquare',
    description: 'Campaigns, applicant intake queue, entrance assessments, and student enrollment',
    submodules: [
      { id: 'dashboard', label: 'Admission Dashboard' },
      { id: 'enquiries', label: 'Enquiries' },
      { id: 'leads', label: 'Leads & Follow-ups' },
      { id: 'applications', label: 'Applications' },
      { id: 'forms', label: 'Admission Forms' },
      { id: 'documents', label: 'Applicant Documents' },
      { id: 'verification', label: 'Verification' },
      { id: 'interviews', label: 'Interviews & Assessments' },
      { id: 'selection', label: 'Selection & Approval' },
      { id: 'processing', label: 'Admission Processing' },
      { id: 'enrollment', label: 'Enrollment' },
      { id: 'fees', label: 'Admission Fees' },
      { id: 'communication', label: 'Admission Communication' },
      { id: 'campaigns', label: 'Admission Campaigns' },
      { id: 'reports', label: 'Admission Reports' },
      { id: 'settings', label: 'Admission Settings' },
    ],
  },
  {
    id: 'students',
    code: '03',
    label: 'Students',
    route: '/students',
    iconName: 'Users',
    description: 'Student 360° directory, guardian linkages, section allocations, and history',
    submodules: [
      { id: 'dashboard', label: 'Student Dashboard' },
      { id: 'all-students', label: 'All Students' },
      { id: 'profiles', label: 'Student Profiles' },
      { id: 'guardians', label: 'Parent & Guardian Records' },
      { id: 'class-section', label: 'Class & Section' },
      { id: 'id-cards', label: 'Student ID & Identity' },
      { id: 'status', label: 'Student Status' },
      { id: 'promotion', label: 'Promotion' },
      { id: 'transfer', label: 'Transfer' },
      { id: 'withdrawal', label: 'Withdrawal' },
      { id: 'readmission', label: 'Re-admission' },
      { id: 'history', label: 'Student History' },
      { id: 'bulk-operations', label: 'Bulk Student Operations' },
      { id: 'import-export', label: 'Import & Export' },
      { id: 'duplicates', label: 'Duplicate Management' },
      { id: 'search', label: 'Student Search' },
      { id: 'requests', label: 'Student Requests' },
      { id: 'settings', label: 'Student Settings' },
    ],
  },
  {
    id: 'academics',
    code: '04',
    label: 'Academics',
    route: '/academics',
    iconName: 'GraduationCap',
    description: 'Curriculum structure, subject allocations, academic sessions, and syllabus tracking',
    submodules: [
      { id: 'dashboard', label: 'Academic Dashboard' },
      { id: 'sessions', label: 'Academic Sessions' },
      { id: 'classes', label: 'Classes' },
      { id: 'sections', label: 'Sections' },
      { id: 'streams', label: 'Streams' },
      { id: 'departments', label: 'Departments' },
      { id: 'subjects', label: 'Subjects' },
      { id: 'subject-groups', label: 'Subject Groups' },
      { id: 'class-subject-mapping', label: 'Class-Subject Mapping' },
      { id: 'student-subject-mapping', label: 'Student-Subject Mapping' },
      { id: 'teacher-subject-mapping', label: 'Teacher-Subject Mapping' },
      { id: 'houses', label: 'Houses' },
      { id: 'calendar', label: 'Academic Calendar' },
      { id: 'working-days', label: 'Working Days' },
      { id: 'policies', label: 'Academic Policies' },
      { id: 'settings', label: 'Academic Settings' },
    ],
  },
  {
    id: 'timetable',
    code: '05',
    label: 'Timetable',
    route: '/timetable',
    iconName: 'Calendar',
    description: 'Period schedules, teacher workload balancing, room booking, and auto-substitutions',
    submodules: [
      { id: 'dashboard', label: 'Timetable Dashboard' },
      { id: 'master-timetable', label: 'Master Timetable' },
      { id: 'class-timetable', label: 'Class Timetable' },
      { id: 'teacher-timetable', label: 'Teacher Timetable' },
      { id: 'room-timetable', label: 'Room Timetable' },
      { id: 'period-structure', label: 'Period Structure' },
      { id: 'subject-scheduling', label: 'Subject Scheduling' },
      { id: 'teacher-workload', label: 'Teacher Workload' },
      { id: 'free-periods', label: 'Free Periods' },
      { id: 'substitutions', label: 'Substitution' },
      { id: 'conflicts', label: 'Timetable Conflicts' },
      { id: 'room-conflicts', label: 'Room Conflicts' },
      { id: 'temporary-changes', label: 'Temporary Changes' },
      { id: 'publishing', label: 'Timetable Publishing' },
      { id: 'reports', label: 'Timetable Reports' },
      { id: 'settings', label: 'Timetable Settings' },
    ],
  },
  {
    id: 'attendance',
    code: '06',
    label: 'Attendance',
    route: '/attendance',
    iconName: 'CalendarCheck',
    description: 'Biometric RFID/face sync, period attendance, employee shifts, and leave approvals',
    submodules: [
      { id: 'dashboard', label: 'Attendance Dashboard' },
      { id: 'todays-attendance', label: "Today's Attendance" },
      { id: 'class-attendance', label: 'Class Attendance' },
      { id: 'period-attendance', label: 'Period Attendance' },
      { id: 'student-attendance', label: 'Student Attendance' },
      { id: 'corrections', label: 'Attendance Corrections' },
      { id: 'leave-management', label: 'Leave Management' },
      { id: 'holiday-management', label: 'Holiday Management' },
      { id: 'late-early', label: 'Late & Early Records' },
      { id: 'summary', label: 'Attendance Summary' },
      { id: 'low-attendance', label: 'Low Attendance' },
      { id: 'alerts', label: 'Attendance Alerts' },
      { id: 'reports', label: 'Attendance Reports' },
      { id: 'settings', label: 'Attendance Settings' },
    ],
  },
  {
    id: 'examination',
    code: '07',
    label: 'Examination',
    route: '/examinations',
    iconName: 'ClipboardList',
    description: 'Question bank generation, hall tickets, seating plans, evaluation, and report cards',
    submodules: [
      { id: 'dashboard', label: 'Examination Dashboard' },
      { id: 'exam-management', label: 'Exam Management' },
      { id: 'test-management', label: 'Test Management' },
      { id: 'assessment-types', label: 'Assessment Types' },
      { id: 'schedule', label: 'Exam Schedule' },
      { id: 'subject-paper-setup', label: 'Subject & Paper Setup' },
      { id: 'student-assignment', label: 'Student Exam Assignment' },
      { id: 'marks-entry', label: 'Marks Entry' },
      { id: 'marks-verification', label: 'Marks Verification' },
      { id: 'grades', label: 'Grades' },
      { id: 'remarks', label: 'Remarks' },
      { id: 'result-calculation', label: 'Result Calculation' },
      { id: 'result-processing', label: 'Result Processing' },
      { id: 'result-publishing', label: 'Result Publishing' },
      { id: 'report-cards', label: 'Report Cards' },
      { id: 'rank-position', label: 'Rank & Position' },
      { id: 'reports', label: 'Result Reports' },
      { id: 'settings', label: 'Examination Settings' },
    ],
  },
  {
    id: 'fees',
    code: '08',
    label: 'Fees',
    route: '/fees',
    iconName: 'CircleDollarSign',
    description: 'Fee structures, student accounts, counter collections, discounts, and defaulters',
    submodules: [
      { id: 'dashboard', label: 'Finance Dashboard' },
      { id: 'structure', label: 'Fee Structure' },
      { id: 'types', label: 'Fee Types' },
      { id: 'assignment', label: 'Student Fee Assignment' },
      { id: 'schedules', label: 'Installments & Schedules' },
      { id: 'collection', label: 'Fee Collection' },
      { id: 'receipts', label: 'Receipts' },
      { id: 'receipt-books', label: 'Receipt Books' },
      { id: 'discounts', label: 'Discounts & Concessions' },
      { id: 'scholarships', label: 'Scholarships' },
      { id: 'refunds', label: 'Refunds' },
      { id: 'cancelled-transactions', label: 'Cancelled Transactions' },
      { id: 'defaulters', label: 'Defaulters' },
      { id: 'reminders', label: 'Fee Reminders' },
      { id: 'payment-methods', label: 'Payment Methods' },
      { id: 'bank-accounts', label: 'Bank Accounts' },
      { id: 'income', label: 'School Income' },
      { id: 'expenses', label: 'School Expenses' },
      { id: 'reconciliation', label: 'Reconciliation' },
      { id: 'certificates', label: 'Fee Certificates' },
      { id: 'reports', label: 'Financial Reports' },
      { id: 'settings', label: 'Finance Settings' },
    ],
  },
  {
    id: 'finance',
    code: '09',
    label: 'Finance',
    route: '/accounting',
    iconName: 'Landmark',
    description: 'Institutional accounting, expense tracking, vendor purchase orders, and reconciliation',
    submodules: [
      { id: 'dashboard', label: 'Finance Dashboard' },
      { id: 'expenses', label: 'Expenses' },
      { id: 'vendors', label: 'Vendors & Purchases' },
      { id: 'accounting', label: 'Accounting' },
      { id: 'budget', label: 'Budget' },
      { id: 'reconciliation', label: 'Bank & Reconciliation' },
      { id: 'controls', label: 'Financial Controls' },
      { id: 'reports', label: 'Finance Reports' },
    ],
  },
  {
    id: 'hr',
    code: '10',
    label: 'HR & Payroll',
    route: '/hr',
    iconName: 'Briefcase',
    description: 'Employee profiles, staff recruitment, salary structures, payroll cycles, and appraisals',
    submodules: [
      { id: 'dashboard', label: 'HR Dashboard' },
      { id: 'directory', label: 'Staff Directory' },
      { id: 'profiles', label: 'Staff Profiles' },
      { id: 'staff-types', label: 'Staff Types' },
      { id: 'departments', label: 'Departments' },
      { id: 'designations', label: 'Designations' },
      { id: 'onboarding', label: 'Joining & Onboarding' },
      { id: 'documents', label: 'Staff Documents' },
      { id: 'attendance', label: 'Staff Attendance' },
      { id: 'leave', label: 'Leave Management' },
      { id: 'assignments', label: 'Work Assignments' },
      { id: 'transfers', label: 'Staff Transfers' },
      { id: 'exit', label: 'Resignation & Exit' },
      { id: 'history', label: 'Employee History' },
      { id: 'salary-structures', label: 'Salary Structures' },
      { id: 'payroll', label: 'Payroll Processing' },
      { id: 'loans', label: 'Advances & Loans' },
      { id: 'deductions', label: 'Deductions' },
      { id: 'payslips', label: 'Payslips' },
      { id: 'payroll-reports', label: 'Payroll Reports' },
      { id: 'reports', label: 'HR Reports' },
      { id: 'settings', label: 'HR Settings' },
    ],
  },
  {
    id: 'library',
    code: '11',
    label: 'Library',
    route: '/library',
    iconName: 'BookOpen',
    description: 'Book cataloging, ISBN barcodes, member circulation, renewals, and overdue fines',
    submodules: [
      { id: 'dashboard', label: 'Library Dashboard' },
      { id: 'catalog', label: 'Book Catalog' },
      { id: 'books', label: 'Books' },
      { id: 'copies', label: 'Book Copies' },
      { id: 'categories', label: 'Categories' },
      { id: 'authors-publishers', label: 'Authors & Publishers' },
      { id: 'members', label: 'Library Members' },
      { id: 'issue', label: 'Issue Books' },
      { id: 'return', label: 'Return Books' },
      { id: 'renewals', label: 'Renewals' },
      { id: 'reservations', label: 'Reservations' },
      { id: 'overdue', label: 'Overdue Books' },
      { id: 'fines', label: 'Fines' },
      { id: 'lost-damaged', label: 'Lost & Damaged Books' },
      { id: 'history', label: 'Book History' },
      { id: 'inventory', label: 'Library Inventory' },
      { id: 'ebooks', label: 'E-books' },
      { id: 'reports', label: 'Library Reports' },
      { id: 'settings', label: 'Library Settings' },
    ],
  },
  {
    id: 'transport',
    code: '12',
    label: 'Transport',
    route: '/transport',
    iconName: 'Bus',
    description: 'Route optimization, vehicle fleet maintenance, driver assignments, and live GPS tracking',
    submodules: [
      { id: 'dashboard', label: 'Transport Dashboard' },
      { id: 'vehicles', label: 'Vehicles' },
      { id: 'routes', label: 'Routes' },
      { id: 'stops', label: 'Stops' },
      { id: 'drivers', label: 'Drivers' },
      { id: 'attendants', label: 'Attendants' },
      { id: 'student-assignment', label: 'Student Transport Assignment' },
      { id: 'vehicle-assignment', label: 'Vehicle Assignment' },
      { id: 'trips', label: 'Trip Management' },
      { id: 'attendance', label: 'Transport Attendance' },
      { id: 'gps-tracking', label: 'GPS & Tracking' },
      { id: 'fees', label: 'Transport Fees' },
      { id: 'documents', label: 'Vehicle Documents' },
      { id: 'maintenance', label: 'Vehicle Maintenance' },
      { id: 'notifications', label: 'Transport Notifications' },
      { id: 'reports', label: 'Transport Reports' },
      { id: 'settings', label: 'Transport Settings' },
    ],
  },
  {
    id: 'hostel',
    code: '13',
    label: 'Hostel',
    route: '/hostel',
    iconName: 'Building',
    description: 'Dormitory blocks, room bed allocation, mess meal planning, and night attendance',
    submodules: [
      { id: 'dashboard', label: 'Hostel Dashboard' },
      { id: 'buildings', label: 'Hostels & Buildings' },
      { id: 'floors', label: 'Floors' },
      { id: 'rooms', label: 'Rooms' },
      { id: 'beds', label: 'Beds' },
      { id: 'student-allocation', label: 'Student Allocation' },
      { id: 'transfers', label: 'Room Transfers' },
      { id: 'attendance', label: 'Hostel Attendance' },
      { id: 'leave', label: 'Leave Management' },
      { id: 'outpass', label: 'Outpass Management' },
      { id: 'visitors', label: 'Visitors' },
      { id: 'incidents', label: 'Hostel Incidents' },
      { id: 'mess', label: 'Mess Management' },
      { id: 'fees', label: 'Hostel Fees' },
      { id: 'inventory', label: 'Hostel Inventory' },
      { id: 'reports', label: 'Hostel Reports' },
      { id: 'settings', label: 'Hostel Settings' },
    ],
  },
  {
    id: 'inventory',
    code: '14',
    label: 'Inventory & Assets',
    route: '/inventory',
    iconName: 'Package',
    description: 'Item cataloging, stock movement, store issue/returns, asset barcodes, and depreciation',
    submodules: [
      { id: 'dashboard', label: 'Inventory Dashboard' },
      { id: 'stock', label: 'Stock' },
      { id: 'categories', label: 'Categories' },
      { id: 'stock-in', label: 'Stock In' },
      { id: 'stock-out', label: 'Stock Out' },
      { id: 'stock-transfer', label: 'Stock Transfer' },
      { id: 'stock-adjustment', label: 'Stock Adjustment' },
      { id: 'purchase-requests', label: 'Purchase Requests' },
      { id: 'quotations', label: 'Quotations' },
      { id: 'vendors', label: 'Vendors' },
      { id: 'purchase-orders', label: 'Purchase Orders' },
      { id: 'goods-receipt', label: 'Goods Receipt' },
      { id: 'low-stock', label: 'Low Stock' },
      { id: 'suppliers', label: 'Suppliers' },
      { id: 'reports', label: 'Procurement Reports' },
      { id: 'settings', label: 'Inventory Settings' },
    ],
  },
  {
    id: 'learning',
    code: '15',
    label: 'Homework & Learning',
    route: '/learning',
    iconName: 'MonitorPlay',
    description: 'Homework assignments, digital learning resources, online classes, and submissions',
    submodules: [
      { id: 'dashboard', label: 'Teaching Dashboard' },
      { id: 'my-classes', label: 'My Classes' },
      { id: 'my-subjects', label: 'My Subjects' },
      { id: 'lesson-planning', label: 'Lesson Planning' },
      { id: 'teaching-plans', label: 'Teaching Plans' },
      { id: 'syllabus-curriculum', label: 'Syllabus & Curriculum' },
      { id: 'topics-chapters', label: 'Topics & Chapters' },
      { id: 'lesson-notes', label: 'Lesson Notes' },
      { id: 'teaching-diary', label: 'Teaching Diary' },
      { id: 'class-activities', label: 'Class Activities' },
      { id: 'learning-objectives', label: 'Learning Objectives' },
      { id: 'syllabus-progress', label: 'Syllabus Progress' },
      { id: 'class-progress', label: 'Class Progress' },
      { id: 'academic-performance', label: 'Academic Performance' },
      { id: 'teacher-planner', label: 'Teacher Planner' },
      { id: 'settings', label: 'Teaching Settings' },
    ],
  },
  {
    id: 'homework',
    code: '15B',
    label: 'Homework & Assignments',
    route: '/homework',
    iconName: 'BookMarked',
    description: 'Homework assignments, worksheets, projects, evaluation, and submission tracking',
    submodules: [
      { id: 'dashboard', label: 'Homework Dashboard' },
      { id: 'homework-list', label: 'Homework' },
      { id: 'assignments', label: 'Assignments' },
      { id: 'worksheets', label: 'Worksheets' },
      { id: 'projects', label: 'Projects' },
      { id: 'question-sets', label: 'Question Sets' },
      { id: 'distribution', label: 'Assignment Distribution' },
      { id: 'submissions', label: 'Student Submissions' },
      { id: 'review', label: 'Submission Review' },
      { id: 'evaluation', label: 'Evaluation & Marks' },
      { id: 'feedback', label: 'Teacher Feedback' },
      { id: 'resubmissions', label: 'Resubmissions' },
      { id: 'late-submissions', label: 'Late Submissions' },
      { id: 'completion-tracking', label: 'Completion Tracking' },
      { id: 'reports', label: 'Homework Reports' },
      { id: 'settings', label: 'Homework Settings' },
    ],
  },
  {
    id: 'resources',
    code: '15C',
    label: 'Learning Resources',
    route: '/resources',
    iconName: 'FolderGit2',
    description: 'Educational content management, study materials, PDFs, videos, and e-books',
    submodules: [
      { id: 'dashboard', label: 'Learning Dashboard' },
      { id: 'notes', label: 'Notes' },
      { id: 'study-materials', label: 'Study Materials' },
      { id: 'pdfs-documents', label: 'PDFs & Documents' },
      { id: 'videos', label: 'Videos' },
      { id: 'ebooks', label: 'E-books' },
      { id: 'external-links', label: 'External Links' },
      { id: 'subject-resources', label: 'Subject Resources' },
      { id: 'chapter-resources', label: 'Chapter Resources' },
      { id: 'teacher-resources', label: 'Teacher Resources' },
      { id: 'shared-resources', label: 'Shared Resources' },
      { id: 'collections', label: 'Learning Collections' },
      { id: 'access', label: 'Resource Access' },
      { id: 'analytics', label: 'Resource Analytics' },
      { id: 'settings', label: 'Learning Settings' },
    ],
  },
  {
    id: 'lms',
    code: '15D',
    label: 'Online Classes',
    route: '/lms',
    iconName: 'Laptop',
    description: 'Virtual learning management, live classes, meeting schedules, and recordings',
    submodules: [
      { id: 'dashboard', label: 'Online Class Dashboard' },
      { id: 'schedule', label: 'Class Schedule' },
      { id: 'create-class', label: 'Create Online Class' },
      { id: 'live-classes', label: 'Live Classes' },
      { id: 'meeting-management', label: 'Meeting Management' },
      { id: 'attendance', label: 'Online Attendance' },
      { id: 'class-materials', label: 'Class Materials' },
      { id: 'content-sharing', label: 'Screen/Content Sharing' },
      { id: 'recordings', label: 'Recordings' },
      { id: 'recorded-classes', label: 'Recorded Classes' },
      { id: 'history', label: 'Online Class History' },
      { id: 'reports', label: 'Online Class Reports' },
      { id: 'settings', label: 'Online Class Settings' },
    ],
  },
  {
    id: 'documents',
    code: '16',
    label: 'Documents & Certificates',
    route: '/documents',
    iconName: 'Files',
    description: 'ID card studio, TC transfer certificates, bonafide verification, and digital vault',
    submodules: [
      { id: 'dashboard', label: 'Documents Dashboard' },
      { id: 'student-documents', label: 'Student Documents' },
      { id: 'staff-documents', label: 'Staff Documents' },
      { id: 'requests', label: 'Document Requests' },
      { id: 'document-templates', label: 'Document Templates' },
      { id: 'certificate-templates', label: 'Certificate Templates' },
      { id: 'bonafide', label: 'Bonafide Certificate' },
      { id: 'transfer', label: 'Transfer Certificate' },
      { id: 'character', label: 'Character Certificate' },
      { id: 'study', label: 'Study Certificate' },
      { id: 'fee-certificate', label: 'Fee Certificate' },
      { id: 'other-certificates', label: 'Other Certificates' },
      { id: 'generation', label: 'Document Generation' },
      { id: 'digital-signature', label: 'Digital Signature' },
      { id: 'verification', label: 'Document Verification' },
      { id: 'issue-history', label: 'Issue History' },
      { id: 'archive', label: 'Document Archive' },
      { id: 'settings', label: 'Document Settings' },
    ],
  },
  {
    id: 'communication',
    code: '17',
    label: 'Communication',
    route: '/communication',
    iconName: 'MessageSquare',
    description: 'School announcements, DLT SMS gateways, WhatsApp broadcasts, and email templates',
    submodules: [
      { id: 'dashboard', label: 'Communication Dashboard' },
      { id: 'announcements', label: 'Announcements' },
      { id: 'circulars', label: 'Circulars' },
      { id: 'sms', label: 'SMS' },
      { id: 'email', label: 'Email' },
      { id: 'push-notifications', label: 'Push Notifications' },
      { id: 'whatsapp', label: 'WhatsApp' },
      { id: 'class-communication', label: 'Class Communication' },
      { id: 'parent-communication', label: 'Parent Communication' },
      { id: 'student-communication', label: 'Student Communication' },
      { id: 'staff-communication', label: 'Staff Communication' },
      { id: 'templates', label: 'Message Templates' },
      { id: 'scheduled', label: 'Scheduled Messages' },
      { id: 'sent', label: 'Sent Messages' },
      { id: 'reports', label: 'Delivery Reports' },
      { id: 'settings', label: 'Communication Settings' },
    ],
  },
  {
    id: 'events',
    code: '18',
    label: 'Events & Calendar',
    route: '/events',
    iconName: 'Sparkles',
    description: 'School-wide events, master calendar, PTM meetings, competitions, and holiday schedules',
    submodules: [
      { id: 'dashboard', label: 'Events Dashboard' },
      { id: 'calendar', label: 'School Calendar' },
      { id: 'events', label: 'Events' },
      { id: 'meetings', label: 'Meetings' },
      { id: 'ptm', label: 'Parent-Teacher Meetings' },
      { id: 'staff-meetings', label: 'Staff Meetings' },
      { id: 'functions', label: 'School Functions' },
      { id: 'competitions', label: 'Competitions' },
      { id: 'holidays', label: 'Holidays' },
      { id: 'registration', label: 'Event Registration' },
      { id: 'reminders', label: 'Reminders' },
      { id: 'communication', label: 'Event Communication' },
      { id: 'reports', label: 'Event Reports' },
      { id: 'settings', label: 'Calendar Settings' },
    ],
  },
  {
    id: 'front-office',
    code: '19',
    label: 'Front Office',
    route: '/front-office',
    iconName: 'UserCheck',
    description: 'School reception and front-desk workflow, visitor log, appointments, calls, and gate passes',
    submodules: [
      { id: 'dashboard', label: 'Front Office Dashboard' },
      { id: 'visitors', label: 'Visitors' },
      { id: 'visitor-log', label: 'Visitor Log' },
      { id: 'appointments', label: 'Appointments' },
      { id: 'calls', label: 'Calls' },
      { id: 'enquiries', label: 'General Enquiries' },
      { id: 'requests', label: 'Front Desk Requests' },
      { id: 'gate-passes', label: 'Gate Passes' },
      { id: 'follow-ups', label: 'Visitor Follow-ups' },
      { id: 'calendar', label: 'Reception Calendar' },
      { id: 'history', label: 'Front Office History' },
      { id: 'reports', label: 'Front Office Reports' },
      { id: 'settings', label: 'Front Office Settings' },
    ],
  },
  {
    id: 'surveys',
    code: '19B',
    label: 'Surveys & Forms',
    route: '/communication',
    iconName: 'ClipboardCheck',
    description: 'Generic school form engine, form builder, student/parent/staff surveys, and consent forms',
    submodules: [
      { id: 'dashboard', label: 'Forms Dashboard' },
      { id: 'builder', label: 'Form Builder' },
      { id: 'student-forms', label: 'Student Forms' },
      { id: 'parent-forms', label: 'Parent Forms' },
      { id: 'staff-forms', label: 'Staff Forms' },
      { id: 'surveys', label: 'Surveys' },
      { id: 'feedback', label: 'Feedback' },
      { id: 'polls', label: 'Polls' },
      { id: 'consent-forms', label: 'Consent Forms' },
      { id: 'registration-forms', label: 'Registration Forms' },
      { id: 'approvals', label: 'Form Approvals' },
      { id: 'responses', label: 'Responses' },
      { id: 'response-analysis', label: 'Response Analysis' },
      { id: 'templates', label: 'Form Templates' },
      { id: 'settings', label: 'Form Settings' },
    ],
  },
  {
    id: 'complaints',
    code: '19C',
    label: 'Complaints & Grievances',
    route: '/front-office',
    iconName: 'HeartHandshake',
    description: 'Complete complaint resolution workflow, grievance inbox, escalation, and investigation',
    submodules: [
      { id: 'dashboard', label: 'Complaints Dashboard' },
      { id: 'types', label: 'Complaint Types' },
      { id: 'new-complaint', label: 'New Complaint' },
      { id: 'inbox', label: 'Complaint Inbox' },
      { id: 'assignment', label: 'Assignment' },
      { id: 'investigation', label: 'Investigation' },
      { id: 'communication', label: 'Communication' },
      { id: 'escalation', label: 'Escalation' },
      { id: 'resolution', label: 'Resolution' },
      { id: 'closure', label: 'Closure' },
      { id: 'history', label: 'Complaint History' },
      { id: 'reports', label: 'Complaint Reports' },
      { id: 'settings', label: 'Complaint Settings' },
    ],
  },
  {
    id: 'administration',
    code: '20',
    label: 'Assets & Maintenance',
    route: '/administration',
    iconName: 'Wrench',
    description: 'Physical school assets, asset registers, preventive maintenance, warranties, and AMC contracts',
    submodules: [
      { id: 'dashboard', label: 'Assets Dashboard' },
      { id: 'register', label: 'Asset Register' },
      { id: 'categories', label: 'Asset Categories' },
      { id: 'assignment', label: 'Asset Assignment' },
      { id: 'locations', label: 'Asset Locations' },
      { id: 'history', label: 'Asset History' },
      { id: 'maintenance-requests', label: 'Maintenance Requests' },
      { id: 'work-orders', label: 'Maintenance Work Orders' },
      { id: 'repairs', label: 'Repairs' },
      { id: 'preventive-maintenance', label: 'Preventive Maintenance' },
      { id: 'service-contracts', label: 'Service Contracts' },
      { id: 'warranty', label: 'Warranty' },
      { id: 'amc-management', label: 'AMC Management' },
      { id: 'disposal', label: 'Asset Disposal' },
      { id: 'reports', label: 'Maintenance Reports' },
      { id: 'settings', label: 'Asset Settings' },
    ],
  },
  {
    id: 'portal',
    code: '21',
    label: 'Parent & Student Portal',
    route: '/portal',
    iconName: 'GraduationCap',
    description: 'Dedicated student & guardian portal for grades, attendance, fees, and leave applications',
    submodules: [
      { id: 'home', label: 'Home' },
      { id: 'academics', label: 'Academics' },
      { id: 'calendar', label: 'Calendar' },
      { id: 'communication', label: 'Communication' },
      { id: 'profile', label: 'Profile & Services' },
    ],
  },
  {
    id: 'reports',
    code: '22',
    label: 'Reports & Analytics',
    route: '/reports',
    iconName: 'BarChart3',
    description: 'Reporting workspace for operational users, cross-module analytics, custom report builder, and scheduled exports',
    submodules: [
      { id: 'dashboard', label: 'Reports Dashboard' },
      { id: 'student-reports', label: 'Student Reports' },
      { id: 'admission-reports', label: 'Admission Reports' },
      { id: 'attendance-reports', label: 'Attendance Reports' },
      { id: 'academic-reports', label: 'Academic Reports' },
      { id: 'examination-reports', label: 'Examination Reports' },
      { id: 'fee-reports', label: 'Fee Reports' },
      { id: 'hr-reports', label: 'HR Reports' },
      { id: 'library-reports', label: 'Library Reports' },
      { id: 'transport-reports', label: 'Transport Reports' },
      { id: 'inventory-reports', label: 'Inventory Reports' },
      { id: 'activity-reports', label: 'Activity Reports' },
      { id: 'custom-reports', label: 'Custom Reports' },
      { id: 'report-builder', label: 'Report Builder' },
      { id: 'data-explorer', label: 'Data Explorer' },
      { id: 'exports', label: 'Exports' },
      { id: 'scheduled-reports', label: 'Scheduled Reports' },
      { id: 'report-templates', label: 'Report Templates' },
    ],
  },
  {
    id: 'compliance',
    code: '22C',
    label: 'Compliance & Records',
    route: '/system',
    iconName: 'ShieldAlert',
    description: 'Indian school compliance model, board/state-specific regulations, mandatory registers, and statutory inspections',
    submodules: [
      { id: 'dashboard', label: 'Compliance Dashboard' },
      { id: 'mandatory-registers', label: 'Mandatory Registers' },
      { id: 'records', label: 'Compliance Records' },
      { id: 'board-records', label: 'Board Records' },
      { id: 'government-records', label: 'Government Records' },
      { id: 'affiliation-records', label: 'Affiliation Records' },
      { id: 'inspection-records', label: 'Inspection Records' },
      { id: 'statutory-documents', label: 'Statutory Documents' },
      { id: 'tasks', label: 'Compliance Tasks' },
      { id: 'deadlines', label: 'Compliance Deadlines' },
      { id: 'retention', label: 'Record Retention' },
      { id: 'reports', label: 'Compliance Reports' },
      { id: 'settings', label: 'Compliance Settings' },
    ],
  },
  {
    id: 'health',
    code: '22A',
    label: 'Student Health',
    route: '/health',
    iconName: 'Stethoscope',
    description: 'Student medical records, health checkups, infirmary logs, allergies, and emergency medical contacts',
    submodules: [
      { id: 'dashboard', label: 'Health Dashboard' },
      { id: 'medical-records', label: 'Student Medical Records' },
      { id: 'checkups', label: 'Health Checkups' },
      { id: 'medical-conditions', label: 'Medical Conditions' },
      { id: 'allergies', label: 'Allergies & Dietary' },
      { id: 'vaccinations', label: 'Vaccination Records' },
      { id: 'infirmary', label: 'Infirmary & Sick Bay' },
      { id: 'incidents', label: 'Injury & Incident Logs' },
      { id: 'emergency', label: 'Emergency Contacts' },
      { id: 'reports', label: 'Health Reports' },
      { id: 'settings', label: 'Health Settings' },
    ],
  },
  {
    id: 'welfare',
    code: '22B',
    label: 'Counselling & Student Support',
    route: '/welfare',
    iconName: 'Brain',
    description: 'Sensitive student welfare workflow, counselling sessions, behaviour records, and support plans',
    submodules: [
      { id: 'dashboard', label: 'Counselling Dashboard' },
      { id: 'cases', label: 'Student Support Cases' },
      { id: 'sessions', label: 'Counselling Sessions' },
      { id: 'behaviour', label: 'Behaviour Records' },
      { id: 'interventions', label: 'Interventions' },
      { id: 'referrals', label: 'Referrals' },
      { id: 'follow-ups', label: 'Follow-ups' },
      { id: 'support-plans', label: 'Support Plans' },
      { id: 'parent-communication', label: 'Parent Communication' },
      { id: 'notes', label: 'Confidential Notes' },
      { id: 'history', label: 'Case History' },
      { id: 'reports', label: 'Support Reports' },
      { id: 'settings', label: 'Counselling Settings' },
    ],
  },
  {
    id: 'security',
    code: '23',
    label: 'Security & Audit',
    route: '/security',
    iconName: 'ShieldCheck',
    description: 'Restricted administrative responsibility, audit logs, login history, device sessions, and security events',
    submodules: [
      { id: 'dashboard', label: 'Security Dashboard' },
      { id: 'audit-logs', label: 'Audit Logs' },
      { id: 'login-history', label: 'Login History' },
      { id: 'sessions', label: 'Device Sessions' },
      { id: 'access-history', label: 'Access History' },
      { id: 'permission-changes', label: 'Permission Changes' },
      { id: 'data-changes', label: 'Data Change History' },
      { id: 'security-events', label: 'Security Events' },
      { id: 'suspicious-activity', label: 'Suspicious Activity' },
      { id: 'account-security', label: 'Account Security' },
      { id: 'session-management', label: 'Session Management' },
      { id: 'reports', label: 'Security Reports' },
      { id: 'settings', label: 'Security Settings' },
    ],
  },
  {
    id: 'system',
    code: '24',
    label: 'School Administration',
    route: '/system',
    iconName: 'Building',
    description: 'Core school-wide configuration, campuses, academic sessions, branding, and policies',
    submodules: [
      { id: 'dashboard', label: 'School Dashboard' },
      { id: 'school-profile', label: 'School Profile' },
      { id: 'campuses-branches', label: 'Campuses & Branches' },
      { id: 'sessions', label: 'Academic Sessions' },
      { id: 'calendar', label: 'School Calendar' },
      { id: 'departments', label: 'Departments' },
      { id: 'classes-sections', label: 'Classes & Sections' },
      { id: 'houses', label: 'Houses' },
      { id: 'branding', label: 'School Branding' },
      { id: 'policies', label: 'School Policies' },
      { id: 'preferences', label: 'General Preferences' },
      { id: 'configuration', label: 'School Configuration' },
      { id: 'numbering-codes', label: 'Numbering & Codes' },
      { id: 'import-export', label: 'Data Import/Export' },
      { id: 'settings', label: 'School Settings' },
    ],
  },
];
