export interface SubmoduleConfig {
  id: string;
  label: string;
  description?: string;
  badge?: string;
}

export interface ModuleConfig {
  id: string;
  code: string;
  label: string;
  route: string;
  iconName: string;
  description: string;
  submodules: SubmoduleConfig[];
}

export const MODULE_REGISTRY: ModuleConfig[] = [
  {
    id: 'dashboard',
    code: '01',
    label: 'Dashboard',
    route: '/',
    iconName: 'LayoutDashboard',
    description: 'Executive command center, role dashboards, and high-level institutional health',
    submodules: [
      { id: 'overview', label: 'Overview' },
      { id: 'operations', label: "Today's Operations" },
      { id: 'alerts', label: 'Alerts & Attention' },
      { id: 'upcoming', label: 'Upcoming' },
      { id: 'tasks', label: 'My Tasks' },
      { id: 'quick-actions', label: 'Quick Actions' },
      { id: 'role-dashboard', label: 'Role Dashboard' },
    ],
  },
  {
    id: 'admissions',
    code: '02',
    label: 'Admissions',
    route: '/admissions',
    iconName: 'UserSquare',
    description: 'Campaigns, applicant intake queue, entrance assessments, and student enrollment',
    submodules: [
      { id: 'dashboard', label: 'Admission Dashboard' },
      { id: 'enquiries', label: 'Enquiries' },
      { id: 'applications', label: 'Applications' },
      { id: 'review', label: 'Applicant Review' },
      { id: 'documents', label: 'Documents' },
      { id: 'interviews', label: 'Interviews & Assessments' },
      { id: 'selection', label: 'Selection & Offers' },
      { id: 'enrollment', label: 'Enrollment' },
      { id: 'settings', label: 'Admission Settings' },
    ],
  },
  {
    id: 'students',
    code: '03',
    label: 'Students',
    route: '/students',
    iconName: 'Users',
    description: 'Student 360° directory, guardian linkages, section allocations, and history',
    submodules: [
      { id: 'dashboard', label: 'Student Dashboard' },
      { id: 'directory', label: 'Student Directory' },
      { id: 'profiles', label: 'Student Profiles' },
      { id: 'guardians', label: 'Guardians & Family' },
      { id: 'classes', label: 'Class & Section' },
      { id: 'groups', label: 'Student Groups' },
      { id: 'status', label: 'Student Status' },
      { id: 'documents', label: 'Student Documents' },
      { id: 'history', label: 'Student History' },
      { id: 'import-export', label: 'Student Import & Export' },
    ],
  },
  {
    id: 'academics',
    code: '04',
    label: 'Academics',
    route: '/academics',
    iconName: 'GraduationCap',
    description: 'Curriculum structure, subject allocations, academic sessions, and syllabus tracking',
    submodules: [
      { id: 'dashboard', label: 'Academic Dashboard' },
      { id: 'structure', label: 'Academic Structure' },
      { id: 'classes-sections', label: 'Classes & Sections' },
      { id: 'subjects', label: 'Subjects' },
      { id: 'curriculum', label: 'Curriculum' },
      { id: 'sessions', label: 'Academic Sessions' },
      { id: 'assignments', label: 'Teachers & Subject Assignment' },
      { id: 'planning', label: 'Academic Planning' },
      { id: 'calendar', label: 'Academic Calendar' },
      { id: 'settings', label: 'Academic Settings' },
    ],
  },
  {
    id: 'timetable',
    code: '05',
    label: 'Timetable',
    route: '/timetable',
    iconName: 'Calendar',
    description: 'Period schedules, teacher workload balancing, room booking, and auto-substitutions',
    submodules: [
      { id: 'dashboard', label: 'Timetable Dashboard' },
      { id: 'config', label: 'Schedule Configuration' },
      { id: 'class-timetable', label: 'Class Timetable' },
      { id: 'teacher-timetable', label: 'Teacher Timetable' },
      { id: 'rooms-resources', label: 'Rooms & Resources' },
      { id: 'substitutions', label: 'Substitutions' },
      { id: 'exam-events', label: 'Exam & Event Scheduling' },
      { id: 'versions', label: 'Timetable Versions' },
    ],
  },
  {
    id: 'attendance',
    code: '06',
    label: 'Attendance',
    route: '/attendance',
    iconName: 'CalendarCheck',
    description: 'Biometric RFID/face sync, period attendance, employee shifts, and leave approvals',
    submodules: [
      { id: 'dashboard', label: 'Attendance Dashboard' },
      { id: 'student-attendance', label: 'Student Attendance' },
      { id: 'period-attendance', label: 'Period Attendance' },
      { id: 'employee-attendance', label: 'Employee Attendance' },
      { id: 'leave', label: 'Leave' },
      { id: 'regularization', label: 'Corrections & Regularization' },
      { id: 'biometric-devices', label: 'Devices & Biometrics' },
      { id: 'reports', label: 'Attendance Reports' },
    ],
  },
  {
    id: 'examination',
    code: '07',
    label: 'Examination',
    route: '/examinations',
    iconName: 'ClipboardList',
    description: 'Question bank generation, hall tickets, seating plans, evaluation, and report cards',
    submodules: [
      { id: 'dashboard', label: 'Examination Dashboard' },
      { id: 'exams', label: 'Exams' },
      { id: 'tests', label: 'Tests & Assessments' },
      { id: 'question-bank', label: 'Question Bank' },
      { id: 'question-papers', label: 'Question Papers' },
      { id: 'schedule', label: 'Exam Schedule' },
      { id: 'hall-tickets', label: 'Hall Tickets' },
      { id: 'seating-invigilation', label: 'Seating & Invigilation' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'results', label: 'Results & Report Cards' },
      { id: 'reports', label: 'Examination Reports' },
    ],
  },
  {
    id: 'fees',
    code: '08',
    label: 'Fees',
    route: '/fees',
    iconName: 'CircleDollarSign',
    description: 'Fee structures, student accounts, counter collections, discounts, and defaulters',
    submodules: [
      { id: 'dashboard', label: 'Fee Dashboard' },
      { id: 'structures', label: 'Fee Structures' },
      { id: 'student-accounts', label: 'Student Accounts' },
      { id: 'collections', label: 'Collections' },
      { id: 'discounts', label: 'Discounts & Scholarships' },
      { id: 'payments', label: 'Payments & Refunds' },
      { id: 'dues', label: 'Dues & Defaulters' },
      { id: 'reports', label: 'Fee Reports' },
      { id: 'settings', label: 'Fee Settings' },
    ],
  },
  {
    id: 'finance',
    code: '09',
    label: 'Finance',
    route: '/accounting',
    iconName: 'Landmark',
    description: 'Institutional accounting, expense tracking, vendor purchase orders, and reconciliation',
    submodules: [
      { id: 'dashboard', label: 'Finance Dashboard' },
      { id: 'expenses', label: 'Expenses' },
      { id: 'vendors', label: 'Vendors & Purchases' },
      { id: 'accounting', label: 'Accounting' },
      { id: 'budget', label: 'Budget' },
      { id: 'reconciliation', label: 'Bank & Reconciliation' },
      { id: 'controls', label: 'Financial Controls' },
      { id: 'reports', label: 'Finance Reports' },
    ],
  },
  {
    id: 'hr',
    code: '10',
    label: 'HR & Payroll',
    route: '/hr',
    iconName: 'Briefcase',
    description: 'Employee profiles, staff recruitment, salary structures, payroll cycles, and appraisals',
    submodules: [
      { id: 'dashboard', label: 'HR Dashboard' },
      { id: 'directory', label: 'Employee Directory' },
      { id: 'profiles', label: 'Employee Profiles' },
      { id: 'recruitment', label: 'Recruitment' },
      { id: 'attendance-leave', label: 'Attendance & Leave' },
      { id: 'payroll', label: 'Payroll' },
      { id: 'salary-structure', label: 'Salary Structure' },
      { id: 'performance', label: 'Performance' },
      { id: 'documents', label: 'Employee Documents' },
      { id: 'reports', label: 'HR Reports' },
    ],
  },
  {
    id: 'library',
    code: '11',
    label: 'Library',
    route: '/library',
    iconName: 'BookOpen',
    description: 'Book cataloging, ISBN barcodes, member circulation, renewals, and overdue fines',
    submodules: [
      { id: 'dashboard', label: 'Library Dashboard' },
      { id: 'catalog', label: 'Catalog & Discovery' },
      { id: 'books', label: 'Books & Collection' },
      { id: 'members', label: 'Members' },
      { id: 'issue-return', label: 'Circulation' },
      { id: 'reservations', label: 'Reservations & Requests' },
      { id: 'fines', label: 'Fines & Accounts' },
      { id: 'digital', label: 'Digital Library' },
      { id: 'reports', label: 'Library Reports & Settings' },
    ],
  },
  {
    id: 'transport',
    code: '12',
    label: 'Transport',
    route: '/transport',
    iconName: 'Bus',
    description: 'Route optimization, vehicle fleet maintenance, driver assignments, and live GPS tracking',
    submodules: [
      { id: 'dashboard', label: 'Transport Dashboard' },
      { id: 'routes', label: 'Routes & Stops' },
      { id: 'fleet', label: 'Fleet & Vehicles' },
      { id: 'drivers', label: 'Drivers & Staff' },
      { id: 'student-transport', label: 'Student Transport' },
      { id: 'trips', label: 'Trips & Operations' },
      { id: 'gps', label: 'GPS & Live Tracking' },
      { id: 'incidents', label: 'Safety & Incidents' },
      { id: 'maintenance', label: 'Maintenance & Fuel' },
      { id: 'fees-reports', label: 'Transport Fees & Reports' },
    ],
  },
  {
    id: 'hostel',
    code: '13',
    label: 'Hostel',
    route: '/hostel',
    iconName: 'Building',
    description: 'Dormitory blocks, room bed allocation, mess meal planning, and night attendance',
    submodules: [
      { id: 'dashboard', label: 'Hostel Dashboard' },
      { id: 'buildings', label: 'Hostel & Buildings' },
      { id: 'rooms', label: 'Rooms & Beds' },
      { id: 'residents', label: 'Student Residents' },
      { id: 'attendance', label: 'Hostel Attendance' },
      { id: 'outpass', label: 'Leave & Outpass' },
      { id: 'mess', label: 'Mess & Meals' },
      { id: 'visitors', label: 'Visitors & Security' },
      { id: 'complaints', label: 'Complaints & Maintenance' },
      { id: 'fees-reports', label: 'Hostel Fees & Reports' },
    ],
  },
  {
    id: 'inventory',
    code: '14',
    label: 'Inventory & Assets',
    route: '/inventory',
    iconName: 'Package',
    description: 'Item cataloging, stock movement, store issue/returns, asset barcodes, and depreciation',
    submodules: [
      { id: 'dashboard', label: 'Inventory Dashboard' },
      { id: 'catalog', label: 'Items & Catalog' },
      { id: 'stock', label: 'Stock & Warehouses' },
      { id: 'procurement', label: 'Purchase & Procurement' },
      { id: 'goods-receipt', label: 'Goods Receipt & Inward' },
      { id: 'assets', label: 'Asset Management' },
      { id: 'issue-transfer', label: 'Issue & Transfer' },
      { id: 'maintenance', label: 'Maintenance & Repairs' },
      { id: 'audit-disposal', label: 'Stock Audit & Disposal' },
      { id: 'reports-settings', label: 'Reports & Settings' },
    ],
  },
  {
    id: 'learning',
    code: '15',
    label: 'Homework & Learning',
    route: '/learning',
    iconName: 'MonitorPlay',
    description: 'Homework assignments, digital learning resources, online classes, and submissions',
    submodules: [
      { id: 'dashboard', label: 'Learning Dashboard' },
      { id: 'lessons', label: 'Lessons & Course Content' },
      { id: 'homework', label: 'Homework & Assignments' },
      { id: 'resources', label: 'Learning Resources' },
      { id: 'quizzes', label: 'Quizzes & Practice' },
      { id: 'evaluation', label: 'Submission & Evaluation' },
      { id: 'study-plans', label: 'Study Plans & Paths' },
      { id: 'progress', label: 'Student Progress' },
      { id: 'teacher-workspace', label: 'Teacher Workspace' },
      { id: 'analytics-settings', label: 'Analytics & Settings' },
    ],
  },
  {
    id: 'documents',
    code: '16',
    label: 'Documents & Certificates',
    route: '/documents',
    iconName: 'Files',
    description: 'ID card studio, TC transfer certificates, bonafide verification, and digital vault',
    submodules: [
      { id: 'dashboard', label: 'Document Dashboard' },
      { id: 'vault', label: 'Document Vault' },
      { id: 'verification', label: 'Collection & Verification' },
      { id: 'templates', label: 'Certificate Templates' },
      { id: 'generation', label: 'Certificate Generation' },
      { id: 'approvals', label: 'Approval & Digital Signing' },
      { id: 'issuance', label: 'Issuance & Delivery' },
      { id: 'requests', label: 'Requests & Applications' },
      { id: 'history', label: 'Verification & History' },
      { id: 'reports-settings', label: 'Reports & Settings' },
    ],
  },
  {
    id: 'communication',
    code: '17',
    label: 'Communication',
    route: '/communication',
    iconName: 'MessageSquare',
    description: 'School announcements, DLT SMS gateways, WhatsApp broadcasts, and email templates',
    submodules: [
      { id: 'dashboard', label: 'Communication Dashboard' },
      { id: 'inbox', label: 'Inbox & Conversations' },
      { id: 'announcements', label: 'Announcements & Notices' },
      { id: 'chat', label: 'Messaging & Chat' },
      { id: 'channels', label: 'SMS, Email & Push' },
      { id: 'broadcasts', label: 'Campaigns & Broadcasts' },
      { id: 'templates', label: 'Templates & Library' },
      { id: 'automations', label: 'Events & Automations' },
      { id: 'analytics', label: 'Communication Analytics' },
      { id: 'settings', label: 'Settings & Governance' },
    ],
  },
  {
    id: 'events',
    code: '18',
    label: 'Events & Activities',
    route: '/events',
    iconName: 'Sparkles',
    description: 'Annual sports day, academic symposiums, club activities, registrations, and media gallery',
    submodules: [
      { id: 'dashboard', label: 'Events Dashboard' },
      { id: 'school-events', label: 'School Events' },
      { id: 'academic-events', label: 'Academic Events' },
      { id: 'sports', label: 'Sports' },
      { id: 'clubs', label: 'Clubs & Activities' },
      { id: 'competitions', label: 'Competitions' },
      { id: 'registrations', label: 'Registrations' },
      { id: 'gallery', label: 'Gallery' },
      { id: 'certificates', label: 'Certificates' },
      { id: 'reports', label: 'Event Reports' },
    ],
  },
  {
    id: 'front-office',
    code: '19',
    label: 'Front Office & Enquiries',
    route: '/front-office',
    iconName: 'UserCheck',
    description: 'Front desk reception, visitor gate passes, enquiry leads, phone calls, and complaints',
    submodules: [
      { id: 'dashboard', label: 'Front Office Dashboard' },
      { id: 'enquiries', label: 'Enquiries' },
      { id: 'visitors', label: 'Visitors' },
      { id: 'appointments', label: 'Appointments' },
      { id: 'calls', label: 'Calls & Follow-ups' },
      { id: 'reception', label: 'Reception' },
      { id: 'complaints', label: 'Complaints' },
      { id: 'lost-found', label: 'Lost & Found' },
      { id: 'reports', label: 'Front Office Reports' },
    ],
  },
  {
    id: 'administration',
    code: '20',
    label: 'School Administration',
    route: '/administration',
    iconName: 'Building',
    description: 'School profile, campus branches, academic sessions, holiday calendars, and policies',
    submodules: [
      { id: 'dashboard', label: 'School Dashboard' },
      { id: 'profile', label: 'School Profile' },
      { id: 'campuses', label: 'Campuses' },
      { id: 'academic-sessions', label: 'Academic Sessions' },
      { id: 'departments', label: 'Departments' },
      { id: 'designations', label: 'Designations' },
      { id: 'working-holidays', label: 'Working Days & Holidays' },
      { id: 'policies', label: 'School Policies' },
      { id: 'workflows', label: 'Workflow Configuration' },
      { id: 'settings', label: 'School Settings' },
    ],
  },
  {
    id: 'portal',
    code: '21',
    label: 'Parent & Student Portal',
    route: '/portal',
    iconName: 'GraduationCap',
    description: 'Dedicated student & guardian portal for grades, attendance, fees, and leave applications',
    submodules: [
      { id: 'dashboard', label: 'Portal Dashboard' },
      { id: 'student-profile', label: 'Student Profile' },
      { id: 'academics', label: 'Academics' },
      { id: 'attendance', label: 'Attendance' },
      { id: 'timetable', label: 'Timetable' },
      { id: 'homework', label: 'Homework & Learning' },
      { id: 'exams-results', label: 'Examination & Results' },
      { id: 'fees-payments', label: 'Fees & Payments' },
      { id: 'communication', label: 'Communication' },
      { id: 'service-requests', label: 'Requests & Services' },
    ],
  },
  {
    id: 'reports',
    code: '22',
    label: 'Reports & Analytics',
    route: '/reports',
    iconName: 'BarChart3',
    description: 'Cross-module executive business intelligence, custom report builder, and scheduled PDF exports',
    submodules: [
      { id: 'dashboard', label: 'Reports Dashboard' },
      { id: 'student-reports', label: 'Student Reports' },
      { id: 'academic-reports', label: 'Academic Reports' },
      { id: 'attendance-reports', label: 'Attendance Reports' },
      { id: 'exam-reports', label: 'Examination Reports' },
      { id: 'fee-reports', label: 'Fee Reports' },
      { id: 'finance-reports', label: 'Finance Reports' },
      { id: 'hr-reports', label: 'HR Reports' },
      { id: 'operations-reports', label: 'Operations Reports' },
      { id: 'custom-reports', label: 'Custom Reports' },
      { id: 'scheduled-reports', label: 'Scheduled Reports' },
      { id: 'data-export', label: 'Data Export' },
    ],
  },
  {
    id: 'security',
    code: '23',
    label: 'Security & Audit',
    route: '/security',
    iconName: 'ShieldCheck',
    description: 'Immutable system audit trails, login session monitors, data change tracking, and compliance',
    submodules: [
      { id: 'dashboard', label: 'Security Dashboard' },
      { id: 'activity-logs', label: 'Activity Logs' },
      { id: 'audit-logs', label: 'Audit Logs' },
      { id: 'login-sessions', label: 'Login & Sessions' },
      { id: 'devices', label: 'Devices' },
      { id: 'access-monitoring', label: 'Access Monitoring' },
      { id: 'data-changes', label: 'Data Changes' },
      { id: 'security-alerts', label: 'Security Alerts' },
      { id: 'compliance', label: 'Compliance' },
      { id: 'reports', label: 'Security Reports' },
    ],
  },
  {
    id: 'system',
    code: '24',
    label: 'System Administration',
    route: '/system',
    iconName: 'Settings',
    description: 'Global system configuration, RBAC roles & permissions, API webhooks, and health monitors',
    submodules: [
      { id: 'dashboard', label: 'System Dashboard' },
      { id: 'users', label: 'Users' },
      { id: 'roles-permissions', label: 'Roles & Permissions' },
      { id: 'organizations', label: 'Organizations' },
      { id: 'integrations', label: 'Integrations' },
      { id: 'api-webhooks', label: 'API & Webhooks' },
      { id: 'storage', label: 'Storage' },
      { id: 'backup-recovery', label: 'Backup & Recovery' },
      { id: 'notification-config', label: 'Notifications Configuration' },
      { id: 'settings', label: 'System Settings' },
      { id: 'feature-flags', label: 'Feature Flags' },
      { id: 'system-health', label: 'System Health' },
    ],
  },
];
