/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelfareRouteImport } from './routes/welfare'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LmsRouteImport } from './routes/lms'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HrRouteImport } from './routes/hr'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ExaminationsRouteImport } from './routes/examinations'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'

const WelfareRoute = WelfareRouteImport.update({
  id: '/welfare',
  path: '/welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LmsRoute = LmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationsRoute = ExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/accounting': typeof AccountingRoute
  '/admissions': typeof AdmissionsRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/communication': typeof CommunicationRoute
  '/documents': typeof DocumentsRoute
  '/examinations': typeof ExaminationsRoute
  '/finance': typeof FinanceRoute
  '/hostel': typeof HostelRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/library': typeof LibraryRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/accounting': typeof AccountingRoute
  '/admissions': typeof AdmissionsRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/communication': typeof CommunicationRoute
  '/documents': typeof DocumentsRoute
  '/examinations': typeof ExaminationsRoute
  '/finance': typeof FinanceRoute
  '/hostel': typeof HostelRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/library': typeof LibraryRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/accounting': typeof AccountingRoute
  '/admissions': typeof AdmissionsRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/communication': typeof CommunicationRoute
  '/documents': typeof DocumentsRoute
  '/examinations': typeof ExaminationsRoute
  '/finance': typeof FinanceRoute
  '/hostel': typeof HostelRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/library': typeof LibraryRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/accounting'
    | '/admissions'
    | '/ai'
    | '/attendance'
    | '/communication'
    | '/documents'
    | '/examinations'
    | '/finance'
    | '/hostel'
    | '/hr'
    | '/inventory'
    | '/library'
    | '/lms'
    | '/login'
    | '/reports'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/welfare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/accounting'
    | '/admissions'
    | '/ai'
    | '/attendance'
    | '/communication'
    | '/documents'
    | '/examinations'
    | '/finance'
    | '/hostel'
    | '/hr'
    | '/inventory'
    | '/library'
    | '/lms'
    | '/login'
    | '/reports'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/welfare'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/accounting'
    | '/admissions'
    | '/ai'
    | '/attendance'
    | '/communication'
    | '/documents'
    | '/examinations'
    | '/finance'
    | '/hostel'
    | '/hr'
    | '/inventory'
    | '/library'
    | '/lms'
    | '/login'
    | '/reports'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/welfare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AccountingRoute: typeof AccountingRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AiRoute: typeof AiRoute
  AttendanceRoute: typeof AttendanceRoute
  CommunicationRoute: typeof CommunicationRoute
  DocumentsRoute: typeof DocumentsRoute
  ExaminationsRoute: typeof ExaminationsRoute
  FinanceRoute: typeof FinanceRoute
  HostelRoute: typeof HostelRoute
  HrRoute: typeof HrRoute
  InventoryRoute: typeof InventoryRoute
  LibraryRoute: typeof LibraryRoute
  LmsRoute: typeof LmsRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  TimetableRoute: typeof TimetableRoute
  TransportRoute: typeof TransportRoute
  WelfareRoute: typeof WelfareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welfare': {
      id: '/welfare'
      path: '/welfare'
      fullPath: '/welfare'
      preLoaderRoute: typeof WelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lms': {
      id: '/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof LmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examinations': {
      id: '/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof ExaminationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AccountingRoute: AccountingRoute,
  AdmissionsRoute: AdmissionsRoute,
  AiRoute: AiRoute,
  AttendanceRoute: AttendanceRoute,
  CommunicationRoute: CommunicationRoute,
  DocumentsRoute: DocumentsRoute,
  ExaminationsRoute: ExaminationsRoute,
  FinanceRoute: FinanceRoute,
  HostelRoute: HostelRoute,
  HrRoute: HrRoute,
  InventoryRoute: InventoryRoute,
  LibraryRoute: LibraryRoute,
  LmsRoute: LmsRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  TimetableRoute: TimetableRoute,
  TransportRoute: TransportRoute,
  WelfareRoute: WelfareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
