/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LmsRouteImport } from './routes/lms'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExaminationsRouteImport } from './routes/examinations'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LmsRoute = LmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationsRoute = ExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/examinations': typeof ExaminationsRoute
  '/fees': typeof FeesRoute
  '/homework': typeof HomeworkRoute
  '/learning': typeof LearningRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/examinations': typeof ExaminationsRoute
  '/fees': typeof FeesRoute
  '/homework': typeof HomeworkRoute
  '/learning': typeof LearningRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/examinations': typeof ExaminationsRoute
  '/fees': typeof FeesRoute
  '/homework': typeof HomeworkRoute
  '/learning': typeof LearningRoute
  '/lms': typeof LmsRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/admissions'
    | '/attendance'
    | '/examinations'
    | '/fees'
    | '/homework'
    | '/learning'
    | '/lms'
    | '/login'
    | '/notices'
    | '/portal'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/staff'
    | '/students'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/admissions'
    | '/attendance'
    | '/examinations'
    | '/fees'
    | '/homework'
    | '/learning'
    | '/lms'
    | '/login'
    | '/notices'
    | '/portal'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/staff'
    | '/students'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/admissions'
    | '/attendance'
    | '/examinations'
    | '/fees'
    | '/homework'
    | '/learning'
    | '/lms'
    | '/login'
    | '/notices'
    | '/portal'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/staff'
    | '/students'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AttendanceRoute: typeof AttendanceRoute
  ExaminationsRoute: typeof ExaminationsRoute
  FeesRoute: typeof FeesRoute
  HomeworkRoute: typeof HomeworkRoute
  LearningRoute: typeof LearningRoute
  LmsRoute: typeof LmsRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  PortalRoute: typeof PortalRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StudentsRoute: typeof StudentsRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lms': {
      id: '/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof LmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examinations': {
      id: '/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof ExaminationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AttendanceRoute: AttendanceRoute,
  ExaminationsRoute: ExaminationsRoute,
  FeesRoute: FeesRoute,
  HomeworkRoute: HomeworkRoute,
  LearningRoute: LearningRoute,
  LmsRoute: LmsRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  PortalRoute: PortalRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StudentsRoute: StudentsRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
